/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wethSol from "./WETH.sol";
export type { wethSol };
export type { BasicNft } from "./BasicNft";
export type { BasicNftTwo } from "./BasicNftTwo";
